# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20170531_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_id',
            field=models.CharField(max_length=10),
        ),
    ]
