# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_auto_20170604_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
