# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0010_auto_20170604_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
