# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_auto_20170604_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='flat',
        ),
        migrations.AddField(
            model_name='flat',
            name='availability',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flats.Availability'),
        ),
    ]
