# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0013_auto_20170604_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='city',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rents',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
